site_name: COMP423 Course Notes
theme:
  name: material

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed: #Added content tab extension to help you organize information. Refer to https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
      alternate_style: true
