site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed: #Added content tab extension to help you organize information. Refer to https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences  